base:
  project: heartdisease-project
  random_state: 42
  target_col: target
data_source:
  s3_source: data_given/heart.csv
load_data:
  raw_dataset_csv: data/raw/heart.csv
split_data:
  train_path: data/processed/train_heart.csv
  test_path: data/processed/test_heart.csv
  test_size: 0.2
estimators:
  xgboost:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      learning_rate: 0.1
      l1_ratio: 0.4
      n_estimators: 1000
      max_depth: 5
      min_child_weight: 1
      gamma: 0
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib
